services:
  backend:
    build: .
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - /app/node_modules
      - ./data:/app/data
      - ./service-account.json:/app/service-account.json
    command: sh -c "npm run build && node dist/index.js"
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    platform: linux/amd64
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web interface
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
      MH_UI_BIND_ADDR: 0.0.0.0:8025
      MH_API_BIND_ADDR: 0.0.0.0:8025
      MH_SMTP_BIND_ADDR: 0.0.0.0:1025
    volumes:
      - mailhog_data:/tmp

volumes:
  mailhog_data:
