platform :ios, '15.1'

require_relative '../node_modules/react-native/scripts/react_native_pods'
prepare_react_native_project!

use_frameworks! :linkage => :static

target 'Charmr' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true
  )

  # 🔐 Firebase Auth + Google Sign-In (NO modular headers!)
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end