platform :ios, '15.1'

require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

use_frameworks! :linkage => :static

target 'Charmr' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true
  )

  # Specify the version of PurchasesHybridCommon
  pod 'PurchasesHybridCommon', '13.29.1' # react-native-purchases v8.9.6 required

  # 🔐 Firebase Auth + Google Sign-In (NO modular headers!)
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'GoogleSignIn'

  # Facebook SDK
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

  # Environment variables
  pod 'react-native-config', :path => '../node_modules/react-native-config'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      if target.name == 'hermes'
        target.build_configurations.each do |config|
          config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
        end
      end
    end
  end
end