import React, {useState} from 'react';
import {StyleSheet, View} from 'react-native';
import {
  ActivityIndicator,
  Button,
  Modal,
  Portal,
  Snackbar,
  Text,
  TextInput,
} from 'react-native-paper';
import ImagePicker from 'react-native-image-crop-picker';
import Clipboard from '@react-native-clipboard/clipboard';

interface KeyboardModalProps {
  visible: boolean;
  onDismiss: () => void;
}

const messageStyles = [
  {label: 'Flirty', value: 'flirty'},
  {label: 'Smooth', value: 'smooth'},
  {label: 'Funny', value: 'funny'},
];

const KeyboardModal: React.FC<KeyboardModalProps> = ({visible, onDismiss}) => {
  const [image, setImage] = useState<string | null>(null);
  const [prompt, setPrompt] = useState('');
  const [selectedStyle, setSelectedStyle] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState<string | null>(null);
  const [showSnackbar, setShowSnackbar] = useState(false);

  const pickImage = async () => {
    try {
      const result = await ImagePicker.openPicker({
        mediaType: 'photo',
        cropping: false,
      });
      setImage(result.path);
    } catch (error) {
      console.error('Error picking image:', error);
    }
  };

  const handleSubmit = async () => {
    setLoading(true);
    try {
      // Mock API call
      await new Promise(resolve => setTimeout(resolve, 2000));
      setResponse(
        'Here is a sample response that would be generated by the GPT API. This is just a mock response for testing purposes.',
      );
    } catch (error) {
      console.error('Error generating response:', error);
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = () => {
    if (response) {
      Clipboard.setString(response);
      setShowSnackbar(true);
    }
  };

  return (
    <Portal>
      <Modal
        visible={visible}
        onDismiss={onDismiss}
        contentContainerStyle={styles.modal}>
        <View style={styles.content}>
          <Text variant="headlineSmall" style={styles.title}>
            Magic Keyboard
          </Text>

          <Button mode="outlined" onPress={pickImage} style={styles.button}>
            {image ? 'Change Image' : 'Pick Image'}
          </Button>

          <TextInput
            label="Prompt (optional)"
            value={prompt}
            onChangeText={setPrompt}
            style={styles.input}
            multiline
          />

          <View style={styles.dropdownContainer}>
            <Text variant="bodyMedium">Message Style (optional):</Text>
            <View style={styles.styleButtons}>
              {messageStyles.map(style => (
                <Button
                  key={style.value}
                  mode={
                    selectedStyle === style.value ? 'contained' : 'outlined'
                  }
                  onPress={() => setSelectedStyle(style.value)}
                  style={styles.styleButton}>
                  {style.label}
                </Button>
              ))}
            </View>
          </View>

          <Button
            mode="contained"
            onPress={handleSubmit}
            style={styles.button}
            loading={loading}>
            Generate Response
          </Button>

          {loading && (
            <View style={styles.loadingContainer}>
              <ActivityIndicator size="large" />
              <Text style={styles.loadingText}>Generating response...</Text>
            </View>
          )}

          {response && (
            <View style={styles.responseContainer}>
              <Text variant="bodyLarge" style={styles.responseLabel}>
                Response:
              </Text>
              <Text
                variant="bodyMedium"
                style={styles.responseText}
                onPress={copyToClipboard}>
                {response}
              </Text>
              <Text variant="bodySmall" style={styles.tapToCopy}>
                Tap to copy
              </Text>
            </View>
          )}
        </View>
      </Modal>

      <Snackbar
        visible={showSnackbar}
        onDismiss={() => setShowSnackbar(false)}
        duration={2000}>
        Copied to clipboard!
      </Snackbar>
    </Portal>
  );
};

const styles = StyleSheet.create({
  modal: {
    backgroundColor: 'white',
    margin: 20,
    padding: 20,
    borderRadius: 8,
  },
  content: {
    gap: 16,
  },
  title: {
    textAlign: 'center',
    marginBottom: 8,
  },
  button: {
    marginTop: 8,
  },
  input: {
    marginTop: 8,
  },
  dropdownContainer: {
    marginTop: 8,
  },
  styleButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  styleButton: {
    flex: 1,
    marginHorizontal: 4,
  },
  loadingContainer: {
    alignItems: 'center',
    marginTop: 16,
  },
  loadingText: {
    marginTop: 8,
  },
  responseContainer: {
    marginTop: 16,
    padding: 16,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
  },
  responseLabel: {
    marginBottom: 8,
  },
  responseText: {
    lineHeight: 24,
  },
  tapToCopy: {
    marginTop: 8,
    textAlign: 'center',
    color: '#666',
  },
});

export default KeyboardModal;
